#!/bin/bash
###

# Predefined values

# If you don't specify nothing here, the script must use zenity for ask you this values

# Don't specify UTF-8 at the end, this is only for load file from languages folder of this script
#LANGUAGE="en_US"
# 0 for accept license, if it isn't accepted it must don't work ;)
#LICENSE=0
# Default device for the SD card
#DEVICE="/dev/mmcblk0"
# Default hostname for Hackberry
#HOSTNAME="HackBerryan"
# Default MAC Address
#MAC_ADDRESS="11:22:33:44:55:66"
# Default work directory where script must work
#WORK_DIR="$HOME/${HOSTNAME}-temp"
# Default ARM Compiler
#ARM_COMPILER_VERSION="gcc-4.6-arm-linux-gnueabihf"
# Default language for the system
#IMG_LANG="en_US.UTF-8"
# Default root password
#ROOT_PASS="root"
# Your wifi name
#WIFI_NETWORK_NAME="YOUR_WIFI_NAME"
# Your wifi pass
#WIFI_NETWORK_PASS="YOUR_WIFI_PASSWORD"
# Your SD card space (this is used for the rootfs image file create between generation)
#SD_SPACE="4096"
# Number of processor detected (auto-detected or specify your desired value)
#THREADS=`cat /proc/cpuinfo | grep processor | wc -l`
